---

- name: Download docker Software
  get_url:
    url: "{{item.url}}"
    dest: "/tmp/{{item.name}}"
    validate_certs: no
  with_items:
    - { url: "{{docker | default([]) }}", name: 'docker-19.03.0.tgz' }
  tags:
    - download


- name: Extract EAP Archive
  unarchive: 
    dest: /etc/
    src: "/tmp/docker-19.03.0.tgz"
    creates: "/etc/docker"
    owner: root 
    group: root
    mode: 0777
    copy: no


- name: Transfer file from ServerA to ServerB
  synchronize:
    src: /etc/docker/
    dest: /usr/bin/
  delegate_to: "{{ inventory_hostname }}"


- name: copy service file
  copy:
    src: docker.service
    dest: /etc/systemd/system/
    owner: root
    group: root
  become: true
  become_user: root
  tags: copy

- name: reload daemon
  shell: systemctl daemon-reload


- name: start docker service
  systemd: 
    name: docker.service
    state: restarted
  become: true
  become_user: root


- name: to verify that docker installed 
  shell: docker run hello-world
  tags: image


- name: run containers
  shell: docker run -itd --name CON-1 -p 9966:9966 springcommunity/spring-petclinic-rest

- name: run containers
  shell: docker run -itd --name CON-2 -p 9967:9966 springcommunity/spring-petclinic-rest

- name: run containers
  shell: docker run -itd --name CON-3 -p 9968:9966 springcommunity/spring-petclinic-rest


